baseURL = "https://slyracoon23-blog.netlify.app"
disqusShortname = "slyracoon23blog"
languageCode = "en-us"
languageName = "En"
theme = "nebula"
title = "Nebula | Hugo blog template"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 3
[[menu.main]]
URL = "privacy-policy"
name = "Privacy Policy"
weight = 4
[outputs]
home = ["HTML", "RSS"]
[params]
author = "Themefisher"
bio = "Earl is a Junior at CU Boulder pursuing a degree in Computer Science. Earl’s passions are robotics and rugby. He is the founder of RoboBoat at CU Boulder, a robotics club that focus on designing and building ASV(Autonomous Surface Vehicles) for the annual Roboboat International Competition"
contact_form_action = "http://0.0.0.0:8000"
copyright = "Design By [Themefisher](https://themefisher.com/) Develop By [Gethugothemes](https://gethugothemes.com/)"
description = "This is meta description"
portrait = "images/author.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
icon = "ti-facebook"
link = "#"
title = "facebook"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
title = "twitter"
[[params.social]]
icon = "ti-instagram"
link = "#"
title = "instagram"
[[params.social]]
icon = "ti-github"
link = "#"
title = "github"
[[params.social]]
icon = "ti-linkedin"
link = "#"
title = "linkedin"
